BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_user_alerts_bir';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE user_alerts CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE user_alerts_seq';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -2289 THEN RAISE; END IF; 
END;
/


CREATE SEQUENCE user_alerts_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
/

CREATE TABLE user_alerts (
    alert_id        NUMBER PRIMARY KEY,
    user_id         NUMBER NOT NULL,
    message         VARCHAR2(500) NOT NULL,
    is_read         NUMBER(1) DEFAULT 0 NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_alert_user_v2 FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE OR REPLACE TRIGGER trg_user_alerts_bir
BEFORE INSERT ON user_alerts
FOR EACH ROW
BEGIN
  IF :NEW.alert_id IS NULL THEN
    SELECT user_alerts_seq.NEXTVAL INTO :NEW.alert_id FROM dual;
  END IF;
END;
/