
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER trg_categories_bir';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE categories_seq';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/

CREATE SEQUENCE categories_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
/

CREATE TABLE categories (
    category_id NUMBER NOT NULL PRIMARY KEY,
    user_id NUMBER NOT NULL,                     
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_category_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_user_category_name UNIQUE (user_id, name) 
)
/

CREATE OR REPLACE TRIGGER trg_categories_bir
BEFORE INSERT ON categories
FOR EACH ROW
BEGIN
    IF :NEW.category_id IS NULL THEN
        SELECT categories_seq.NEXTVAL INTO :NEW.category_id FROM dual;
    END IF;
END;
/
